### ISSUE TITLE
Can I measure the size of the hand？

### ISSUE THREAD

**Issue by SeaMyC** [machidyo/MediaPipeHandTracking#1]
Is there a size formula for calculating hand size based on the data of 20 nodes

**Comment by machidyo** [comment]
@SeaMyC 
Not as far as I know. We recognize that only the positional relationship of joints can be acquired in the image.

**Comment by mgyong** [comment]
There is no way to measure the absolute size of the hand as we do not have scale of pixel -> absolute length from the image. You will need to figure a way either from placing an object with absolute length in the image or get calibrated camera settings
