### ISSUE TITLE
Getting hand landmarks without rendering data to the screen.?

### ISSUE THREAD

**Issue by Kiru3014** [machidyo/MediaPipeHandTracking#2]
Hi  I am looking for output with the below points

I'm able to run the media pipe on android and get the landmarks, however, I'd like to see the output without the SurfaceView.
I just want the landmarks(in like a List<>) without any rendering on to the screen.

In 1st Point, if I disable frame layout rendering from the screen from XML I'm not able to deduct any hand points on

![image](https://user-images.githubusercontent.com/36956488/126486245-b94b29a7-4afd-4ba1-9ee5-6d515009c7ad.png)

https://github.com/machidyo/MediaPipeHandTracking/blob/8fa599c67c44754bbd410b48005a6adedde50a22/app/src/main/java/com/example/mediapipehandtracking/MainActivity.kt#L122

**Comment by machidyo** [comment]
@Kiru3014 
I think the code here is what you're looking for.

https://github.com/machidyo/MediaPipeHandTracking/blob/8fa599c67c44754bbd410b48005a6adedde50a22/app/src/main/java/com/example/mediapipehandtracking/MainActivity.kt#L80
