### ISSUE TITLE
How should I fix this mistake?  E/tflite: Next operations are not supported by GPU delegate:

### ISSUE THREAD

**Issue by LMR2018** [machidyo/MediaPipeHandTracking#3]
I/native: I0928 21:04:56.451962 25798 jni_util.cc:40] GetEnv: not attached
I/native: I0928 21:04:56.556967 25756 resource_util_android.cc:53] Successfully loaded: palm_detection.tflite
I/tflite: Initialized TensorFlow Lite runtime.
I/tflite: Created TensorFlow Lite delegate for GPU.
I/native: I0928 21:04:59.444133 25801 resource_util_android.cc:53] Successfully loaded: palm_detection_labelmap.txt
I/native: I0928 21:04:59.509568 25756 resource_util_android.cc:53] Successfully loaded: hand_landmark.tflite
E/tflite: Next operations are not supported by GPU delegate:
    MEAN: Operation is not supported.
    First 160 operations will run on the GPU, and the remaining 7 on the CPU.
E/tflite: external/org_tensorflow/tensorflow/lite/kernels/fully_connected.cc:105 filter->type != kTfLiteFloat32 (10 != 1)
    Node number 155 (FULLY_CONNECTED) failed to prepare.
    external/org_tensorflow/tensorflow/lite/kernels/conv.cc:272 bias->type != input_type (10 != 1)
    Node number 2 (CONV_2D) failed to prepare.

How should I fix this mistake?

**Comment by machidyo** [comment]
@LMR2018 
1. In what environment and how is it running?
2. Did you confirm the procedure of [Getting Started](https://google.github.io/mediapipe/getting_started/android.html) ?
3. This repository is a conversion of [Java code](https://github.com/jiuqiant/mediapipe_multi_hands_tracking_aar_example) as a sample for Kotlin. Do I get the same error when I run it in the original Java code?
